### ISSUE TITLE
build fails with vivado target

### ISSUE THREAD

**Issue by AnttiLukats** [fusesoc/blinky#7]
B:\fuse>fusesoc run --target=nexys_a7 fusesoc:utils:blinky
←[1;37mINFO: Preparing fusesoc:utils:blinky:0←[0m
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\fusesoc.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\fusesoc\main.py", line 604, in main
    args.func(cm, args)
  File "c:\python37\lib\site-packages\fusesoc\main.py", line 262, in run
    flags, args.system_name, args.system, args.backendargs, args.build_root)
  File "c:\python37\lib\site-packages\fusesoc\main.py", line 339, in run_backend
    backend.configure(backendargs)
  File "c:\python37\lib\site-packages\edalize\edatool.py", line 103, in configure
    self.configure_main()
  File "c:\python37\lib\site-packages\edalize\vivado.py", line 70, in configure_main
    template_vars)
  File "c:\python37\lib\site-packages\edalize\edatool.py", line 237, in render_template
    template = self.jinja_env.get_template(os.path.join(template_dir, template_file))
  File "c:\python37\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python37\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python37\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\python37\lib\site-packages\jinja2\loaders.py", line 232, in get_source
    pieces = split_template_path(template)
  File "c:\python37\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: vivado\vivado-project.tcl.j2

**Comment by AnttiLukats** [comment]
it fails with quartus as well, with edalize 1.6.0 also, template not found always error

**Comment by olofk** [comment]
Did edalize 0.1.6 fix Vivado but Quartus is still broken?

Also, can you paste the error log?

**Comment by AnttiLukats** [comment]
fixed, this but for you the error log

:\fuse>fusesoc run --target=de0_nano fusesoc:utils:blinky
[1;37mINFO: Preparing fusesoc:utils:blinky:0←[0m
nable to recognise Quartus version via quartus_sh

AKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
atal: '.tcl' does not exist - don't know how to make it
[1;31mERROR: Failed to build fusesoc:utils:blinky:0 : 'make' exited with an error code←[0m
